### PR TITLE
[Feature] #318 Add an option to put Origin JSON

### PR DESCRIPTION
**Pull request by BOOMeranGG**
[Feature] #318 Add an option to put Origin JSON

### CODE REVIEW

**Comment by wuseal** [comment]
Hello, Thank for contribution, I revewed the code, seems that it  missing the part of generate File logic, can you make up it?, refer here: https://github.com/BOOMeranGG/JsonToKotlinClass/blob/issue-318/src/main/kotlin/wu/seal/jsontokotlin/utils/KotlinClassFileGenerator.kt

**Comment by wuseal** [comment]
Another requirement is append try append unit test for this function

**Comment by BOOMeranGG** [comment]
@wuseal Hello! Thanks for your review. I added logic for File generating and also added unit tests.

**Review by wuseal — APPROVED** [review]
LGTM

**Comment by BOOMeranGG** [comment]
Thanks!
Do I need approval from anyone else? Or it is ready to merge?

**Comment by wuseal** [comment]
Can merge now thanks for your contribution 🎉🎉🎉🎉🎉

**Pull request merged**
