### PR TITLE
Update shortcuts for Mac

### PR DESCRIPTION
**Pull request by mladenrakonjac**

### CODE REVIEW

**Comment by wuseal** [comment]
@mladenrakonjac Is that test Ok default short key with short key `Commd` +`N`?

**Comment by wuseal** [comment]
I just have test ,when on Mac ,the short key is `Option` +`K`

**Comment by mladenrakonjac** [comment]
I just tested it, it works that way too. Bad thing: each time when you press it  ˚ symbol is written to.

**Comment by wuseal** [comment]
@mladenrakonjac Is there any shortcut ke conflict ,If there is .You can modify it

**Comment by wuseal** [comment]
I am sorry I don't understand the bad things just as you sad

**Pull request merged**
