### PR TITLE
refactored 'settings' to 'advanced' in Pop Up Dialog

### LINKED ISSUE #125: Change `Settings` to `Advanced` in the popup dialog
change the text from `Settings` to `Advanced` in the dialog and corresponding documentation in the README.md

image

### PR DESCRIPTION
**Pull request by SuuSoJeat**
Resolve #125 refactored 'settings' to 'advanced' in Pop Up Dialog

### CODE REVIEW

**Comment by wuseal** [comment]
Glad to receive your PR, Now we need to merge your Pull Request into branch 3.2.0, So  Please rebase the merge target branch to `wuseal:3.2.0` 😄

**Comment by kezhenxu94** [comment]
> Need rebase target branch from master to 3.2.0

Actually we can do this on this web page for the contributor (Click edit and change the base branch), but there are conflicts, could you @SuuSoJeat please resolve the conflict? I think we can help to resolve if the contributor need help @wuseal

**Comment by wuseal** [comment]
@kezhenxu94 Yes！of course!

**Comment by wuseal** [comment]
Let's merge it into master branch first, And then merge master into branch 3.2.0, And all pull request from new contributors could  do like this

**Comment by kezhenxu94** [comment]
@SuuSoJeat Thanks for your contributions!

**Comment by SuuSoJeat** [comment]
Oops! Sorry guys! I was caught up in something. Guess, I'm late.

**Pull request merged**
